### ISSUE TITLE
supported-backends.md declares alfred project as "not maintained"

### ISSUE THREAD

**Issue by ecsv** [ffrgb/meshviewer-doc#3]
The documentations declares the alfred project as "not maintained". I would guess that @simonwunderlich has a different opinion about that. Either this sentence was written with a different intention and misses some important parts (which would have avoided this misunderstanding) *or* is a blatant lie.

Right now it states following under "ffmap-backend" 

> Our original base supports ffmap-backend with nodes.json v2. Ffmap-backend uses not maintained alfred.

Please fix this by adjusting the wording according to your original intentions.

**Comment by ecsv** [comment]
This incorrect statement was added by @xf- in https://github.com/ffrgb/meshviewer-doc/commit/a8a58d5ff5fa8e23e80ae592677adf66127c5710

The resulting document is published under https://doc.meshviewer.org/supported-backends.html#ffmap-backend

**Comment by xf-** [comment]
@ecsv my mistake - ffmap-backend has no maintainer https://github.com/ffnord/ffmap-backend
